### PR TITLE
#8 Fixed duplicate import directive

### PR DESCRIPTION
**Pull request by Alamaster99**
I have separated the import directive into another liquid template.

### CODE REVIEW

**Comment by RSuter** [comment]
Updated PR with NJS alignment.

**Comment by RSuter** [comment]
Thanks for the PR!

**Comment by RSuter** [comment]
How are you using this project ATM?

**Comment by Alamaster99** [comment]
Hi! Thanks for the quick fix!

We are developing microservices with asp.net core and my team is responsible for backend services. We are using openapi and Swagger to generate C# controllers and TypeScript clients for the API between frontend and backend. Now we are implementing server push functionality using SignalR. So we wanted to do something similar. 

We have a project with abstract hub classes and we generate nuget package from it and also using SigSpec we generate the TypeScript to be used by Frontend team.

**Comment by RSuter** [comment]
And you are using the sigspec code as copy in your solution? You know that this is an experimental project?

**Comment by Alamaster99** [comment]
Yeah I know it's experimental.  I have made a nuget package out of it (for our dedicated nuget server). 

Is that a problem? I know, that you cannot guarantee anything, but I don't mind as long as the source code is available. It's not a crucial functionality, we can always write the TypeScript manually, but I like this tool.

Are you OK with it?

**Comment by RSuter** [comment]
Of course this is fine, but please dont publish an “inofficial” public nuget package :-)

**Comment by Alamaster99** [comment]
No I am not planning on publishing anything, It is really our private company nuget server.

Thanks again for all your work!

**Pull request merged**
