### PR TITLE
Added a filter for overridden hub lifetime methods 

### PR DESCRIPTION
**Pull request by austinsc**
This PR prevents the operation methods from producing operations like 'OnConnectedAsync' and other methods declared in Hub and Hub<>.

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR, but please move the js commit into a second PR

**Comment by austinsc** [comment]
Oops, meant to separate that.

**Comment by austinsc** [comment]
I'll recreate against the appropriate branch

**Comment by RSuter** [comment]
For the other pr you should use the conversion methods from here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/ConversionUtilities.cs

**Pull request closed without merging**
